import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import { ThemeProvider } from "@/providers/ThemeProvider";
import Footer from "@/components/footer";
import { BackToTopButton } from "@/components/BackToTopButton";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair_Display = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create My first web app using nextjs and shadcn/ui",
  description: "Generated by create next app with shadcn/ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" suppressHydrationWarning
      className={`${inter.variable} ${playfair_Display.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation />
          {children}
           <BackToTopButton />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
